drop table if exists AUTHOR;
drop table if exists AUTHOR_BOOK;
drop table if exists BOOK;
drop table if exists BOOK_AUTHOR;
drop table if exists BOOK_BOOK_COPY;
drop table if exists BOOK_CATEGORY;
drop table if exists BOOK_COPY;
drop table if exists BOOK_COPY_BORROW;
drop table if exists BOOK_COPY_RESERVATION;
drop table if exists BORROW;
drop table if exists BORROW_BOOK_COPY;
drop table if exists CATEGORY;
drop table if exists CATEGORY_BOOK;
drop table if exists LANGUAGE;
drop table if exists LANGUAGE_BOOK;
drop table if exists PENALTY;
drop table if exists PERMISSION;
drop table if exists PERMISSION_USER;
drop table if exists PUBLISHER;
drop table if exists PUBLISHER_BOOK;
drop table if exists RESERVATION;
drop table if exists RESERVATION_BOOK_COPY;
drop table if exists USER;
drop table if exists USER_BORROW;
drop table if exists USER_PENALTY;
drop table if exists USER_RESERVATION;
create table AUTHOR (id integer not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, primary key (id)) type=MyISAM;
create table AUTHOR_BOOK (Author_id integer not null, books_id integer not null, primary key (Author_id, books_id)) type=MyISAM;
create table BOOK (id integer not null, ISBN varchar(255), description varchar(255), edition integer not null, pages integer not null, publication_year smallint, title varchar(255) not null, language_id integer, publisher_id integer, primary key (id)) type=MyISAM;
create table BOOK_AUTHOR (Book_id integer not null, authors_id integer not null, primary key (Book_id, authors_id)) type=MyISAM;
create table BOOK_BOOK_COPY (Book_id integer not null, bookCopies_id integer not null, primary key (Book_id, bookCopies_id)) type=MyISAM;
create table BOOK_CATEGORY (Book_id integer not null, categories_id integer not null, primary key (Book_id, categories_id)) type=MyISAM;
create table BOOK_COPY (id integer not null auto_increment, status integer not null, book_id integer, primary key (id)) type=MyISAM;
create table BOOK_COPY_BORROW (BookCopy_id integer not null, borrows_id integer not null, primary key (BookCopy_id, borrows_id)) type=MyISAM;
create table BOOK_COPY_RESERVATION (BookCopy_id integer not null, reservations_id integer not null, primary key (BookCopy_id, reservations_id)) type=MyISAM;
create table BORROW (id integer not null auto_increment, borrowed_on date not null, due_date date, returned date, user_id integer, primary key (id)) type=MyISAM;
create table BORROW_BOOK_COPY (Borrow_id integer not null, bookCopies_id integer not null, primary key (Borrow_id, bookCopies_id)) type=MyISAM;
create table CATEGORY (id integer not null auto_increment, name varchar(255) not null, primary key (id)) type=MyISAM;
create table CATEGORY_BOOK (Category_id integer not null, books_id integer not null, primary key (Category_id, books_id)) type=MyISAM;
create table LANGUAGE (id integer not null auto_increment, name varchar(255) not null, primary key (id)) type=MyISAM;
create table LANGUAGE_BOOK (Language_id integer not null, books_id integer not null, primary key (Language_id, books_id)) type=MyISAM;
create table PENALTY (id integer not null auto_increment, amount double precision not null, due_date date not null, interest double precision not null, user_id integer, primary key (id)) type=MyISAM;
create table PERMISSION (id integer not null auto_increment, manage_all_users bit not null, manage_books bit not null, manage_members bit not null, primary key (id)) type=MyISAM;
create table PERMISSION_USER (Permission_id integer not null, users_id integer not null, primary key (Permission_id, users_id)) type=MyISAM;
create table PUBLISHER (id integer not null auto_increment, location varchar(255), name varchar(255) not null, primary key (id)) type=MyISAM;
create table PUBLISHER_BOOK (Publisher_id integer not null, books_id integer not null, primary key (Publisher_id, books_id)) type=MyISAM;
create table RESERVATION (id integer not null auto_increment, end_date date not null, start_date date not null, type varchar(255) not null, user_id integer, primary key (id)) type=MyISAM;
create table RESERVATION_BOOK_COPY (Reservation_id integer not null, bookCopies_id integer not null, primary key (Reservation_id, bookCopies_id)) type=MyISAM;
create table USER (id integer not null auto_increment, email varchar(255) not null, login varchar(255) not null, name varchar(255) not null, phone_number varchar(255), surname varchar(255) not null, permission_id integer, primary key (id)) type=MyISAM;
create table USER_BORROW (User_id integer not null, borrows_id integer not null, primary key (User_id, borrows_id)) type=MyISAM;
create table USER_PENALTY (User_id integer not null, pentalties_id integer not null, primary key (User_id, pentalties_id)) type=MyISAM;
create table USER_RESERVATION (User_id integer not null, reservations_id integer not null, primary key (User_id, reservations_id)) type=MyISAM;
alter table BOOK add constraint UK_kkd7aa41jutasor701u64yvs8 unique (ISBN);
alter table BOOK_BOOK_COPY add constraint UK_4jquacwqg21y60g5g79b33uj9 unique (bookCopies_id);
alter table LANGUAGE_BOOK add constraint UK_7prrcqs4yydu44jqcgg9o86wb unique (books_id);
alter table PERMISSION_USER add constraint UK_bd23vse5j0wr4rg9dmrvxk6kq unique (users_id);
alter table PUBLISHER_BOOK add constraint UK_tmropp9l00ommd3hs9e3qk3xd unique (books_id);
alter table USER add constraint UK_oso07pudw19e66bs4yp8hwpux unique (email);
alter table USER add constraint UK_slockai06wyhy7i5c8vnd2o31 unique (login);
alter table USER_BORROW add constraint UK_jyj14utjyhuvqvbqxpeng34wt unique (borrows_id);
alter table USER_PENALTY add constraint UK_ag7acm4j2qsl0pn8j4id87r77 unique (pentalties_id);
alter table USER_RESERVATION add constraint UK_np2co3kslu8gcf6keqb0jtlh4 unique (reservations_id);
alter table AUTHOR_BOOK add constraint FK7vekgbhe0o6r0iaxku6rqtmie foreign key (books_id) references BOOK (id);
alter table AUTHOR_BOOK add constraint FK82yb03xr0gighwxf66390w1t2 foreign key (Author_id) references AUTHOR (id);
alter table BOOK add constraint FKctsex51u9k4o1k692uypo5t00 foreign key (language_id) references LANGUAGE (id);
alter table BOOK add constraint FKqvfng8guxc1p4jgft4c6sjrcd foreign key (publisher_id) references PUBLISHER (id);
alter table BOOK_AUTHOR add constraint FKjc7wg1x9yra815k3cgvqo8v64 foreign key (authors_id) references AUTHOR (id);
alter table BOOK_AUTHOR add constraint FKcpe3nnb7bay7fsg9uhphakt9s foreign key (Book_id) references BOOK (id);
alter table BOOK_BOOK_COPY add constraint FKorg1gomcecx1q78xkwbu5kc79 foreign key (bookCopies_id) references BOOK_COPY (id);
alter table BOOK_BOOK_COPY add constraint FK9jq1bxhgdrv407lhcs1hjytl0 foreign key (Book_id) references BOOK (id);
alter table BOOK_CATEGORY add constraint FKai7p5webscft71hw3copjod92 foreign key (categories_id) references CATEGORY (id);
alter table BOOK_CATEGORY add constraint FKj8rjeonbtbfsqvn9ew2huursj foreign key (Book_id) references BOOK (id);
alter table BOOK_COPY add constraint FKbahwm26a3cg9onugblc5aq3td foreign key (book_id) references BOOK (id);
alter table BOOK_COPY_BORROW add constraint FKg511yv16781e4d8r5krbdgy94 foreign key (borrows_id) references BORROW (id);
alter table BOOK_COPY_BORROW add constraint FK90o6g5wttou8k3jtw9ud30tg5 foreign key (BookCopy_id) references BOOK_COPY (id);
alter table BOOK_COPY_RESERVATION add constraint FK2pgxo6hvpb7tof572rmdhtryv foreign key (reservations_id) references RESERVATION (id);
alter table BOOK_COPY_RESERVATION add constraint FK3tvduqa0qpjk9dc7hnwaw7f95 foreign key (BookCopy_id) references BOOK_COPY (id);
alter table BORROW add constraint FKce9iriou0bnlby6330e9b05i6 foreign key (user_id) references USER (id);
alter table BORROW_BOOK_COPY add constraint FKqj0uacxa71rtnva8jo3cp0xol foreign key (bookCopies_id) references BOOK_COPY (id);
alter table BORROW_BOOK_COPY add constraint FKq2uv071mb9dypor7tp6ptay1a foreign key (Borrow_id) references BORROW (id);
alter table CATEGORY_BOOK add constraint FKg20fvru2uhyb9u8ubtdmnib29 foreign key (books_id) references BOOK (id);
alter table CATEGORY_BOOK add constraint FK4mas29dbqh20hj9rgrrx13013 foreign key (Category_id) references CATEGORY (id);
alter table LANGUAGE_BOOK add constraint FK9wkxyqt70q0pukvoa5c24ri29 foreign key (books_id) references BOOK (id);
alter table LANGUAGE_BOOK add constraint FKqft642svo0sti94uwlu5waqam foreign key (Language_id) references LANGUAGE (id);
alter table PENALTY add constraint FKm6ic8hkdurk2so2295is6vqxy foreign key (user_id) references USER (id);
alter table PERMISSION_USER add constraint FK8vn5mx7g6ol1hdwff69xyfvja foreign key (users_id) references USER (id);
alter table PERMISSION_USER add constraint FKmbvpou13d8y0j8qiv6p7vc3jk foreign key (Permission_id) references PERMISSION (id);
alter table PUBLISHER_BOOK add constraint FK806n7o30vj3ufdnloyxlkjoe4 foreign key (books_id) references BOOK (id);
alter table PUBLISHER_BOOK add constraint FK15kqxcu6f5bwp3idcg8jgxtlx foreign key (Publisher_id) references PUBLISHER (id);
alter table RESERVATION add constraint FKr2u2j7gugmek6gdo7e61mp6jr foreign key (user_id) references USER (id);
alter table RESERVATION_BOOK_COPY add constraint FKryg3x9u513huj6k35rlpk36t2 foreign key (bookCopies_id) references BOOK_COPY (id);
alter table RESERVATION_BOOK_COPY add constraint FKj0m5g695gl625cspf4ssqtjqc foreign key (Reservation_id) references RESERVATION (id);
alter table USER add constraint FK9wice7q5w80yx8dje6cagyyxy foreign key (permission_id) references PERMISSION (id);
alter table USER_BORROW add constraint FKpvdmboys8d467paj1sd1jcy74 foreign key (borrows_id) references BORROW (id);
alter table USER_BORROW add constraint FKlhguhf3hbl7nsngoh6xm3gh4i foreign key (User_id) references USER (id);
alter table USER_PENALTY add constraint FK81u3l9i52xqqv0891vfvmel6l foreign key (pentalties_id) references PENALTY (id);
alter table USER_PENALTY add constraint FKqhsiyis1y4uih88t7rahywdpt foreign key (User_id) references USER (id);
alter table USER_RESERVATION add constraint FKnp5rhwdh0bt4iyx3of4v9jbrv foreign key (reservations_id) references RESERVATION (id);
alter table USER_RESERVATION add constraint FK1tnvc1iymu3r1aj6mfvdo76vh foreign key (User_id) references USER (id);
drop table if exists AUTHOR;
drop table if exists AUTHOR_BOOK;
drop table if exists BOOK;
drop table if exists BOOK_AUTHOR;
drop table if exists BOOK_BOOK_COPY;
drop table if exists BOOK_CATEGORY;
drop table if exists BOOK_COPY;
drop table if exists BOOK_COPY_BORROW;
drop table if exists BOOK_COPY_RESERVATION;
drop table if exists BORROW;
drop table if exists BORROW_BOOK_COPY;
drop table if exists CATEGORY;
drop table if exists CATEGORY_BOOK;
drop table if exists LANGUAGE;
drop table if exists LANGUAGE_BOOK;
drop table if exists PENALTY;
drop table if exists PERMISSION;
drop table if exists PERMISSION_USER;
drop table if exists PUBLISHER;
drop table if exists PUBLISHER_BOOK;
drop table if exists RESERVATION;
drop table if exists RESERVATION_BOOK_COPY;
drop table if exists USER;
drop table if exists USER_BORROW;
drop table if exists USER_PENALTY;
drop table if exists USER_RESERVATION;
create table AUTHOR (id integer not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, primary key (id)) type=MyISAM;
create table AUTHOR_BOOK (Author_id integer not null, books_id integer not null, primary key (Author_id, books_id)) type=MyISAM;
create table BOOK (id integer not null, ISBN varchar(255), description varchar(255), edition integer not null, pages integer not null, publication_year smallint, title varchar(255) not null, language_id integer, publisher_id integer, primary key (id)) type=MyISAM;
create table BOOK_AUTHOR (Book_id integer not null, authors_id integer not null, primary key (Book_id, authors_id)) type=MyISAM;
create table BOOK_BOOK_COPY (Book_id integer not null, bookCopies_id integer not null, primary key (Book_id, bookCopies_id)) type=MyISAM;
create table BOOK_CATEGORY (Book_id integer not null, categories_id integer not null, primary key (Book_id, categories_id)) type=MyISAM;
create table BOOK_COPY (id integer not null auto_increment, status integer not null, book_id integer, primary key (id)) type=MyISAM;
create table BOOK_COPY_BORROW (BookCopy_id integer not null, borrows_id integer not null, primary key (BookCopy_id, borrows_id)) type=MyISAM;
create table BOOK_COPY_RESERVATION (BookCopy_id integer not null, reservations_id integer not null, primary key (BookCopy_id, reservations_id)) type=MyISAM;
create table BORROW (id integer not null auto_increment, borrowed_on date not null, due_date date, returned date, user_id integer, primary key (id)) type=MyISAM;
create table BORROW_BOOK_COPY (Borrow_id integer not null, bookCopies_id integer not null, primary key (Borrow_id, bookCopies_id)) type=MyISAM;
create table CATEGORY (id integer not null auto_increment, name varchar(255) not null, primary key (id)) type=MyISAM;
create table CATEGORY_BOOK (Category_id integer not null, books_id integer not null, primary key (Category_id, books_id)) type=MyISAM;
create table LANGUAGE (id integer not null auto_increment, name varchar(255) not null, primary key (id)) type=MyISAM;
create table LANGUAGE_BOOK (Language_id integer not null, books_id integer not null, primary key (Language_id, books_id)) type=MyISAM;
create table PENALTY (id integer not null auto_increment, amount double precision not null, due_date date not null, interest double precision not null, user_id integer, primary key (id)) type=MyISAM;
create table PERMISSION (id integer not null auto_increment, manage_all_users bit not null, manage_books bit not null, manage_members bit not null, primary key (id)) type=MyISAM;
create table PERMISSION_USER (Permission_id integer not null, users_id integer not null, primary key (Permission_id, users_id)) type=MyISAM;
create table PUBLISHER (id integer not null auto_increment, location varchar(255), name varchar(255) not null, primary key (id)) type=MyISAM;
create table PUBLISHER_BOOK (Publisher_id integer not null, books_id integer not null, primary key (Publisher_id, books_id)) type=MyISAM;
create table RESERVATION (id integer not null auto_increment, end_date date not null, start_date date not null, type varchar(255) not null, user_id integer, primary key (id)) type=MyISAM;
create table RESERVATION_BOOK_COPY (Reservation_id integer not null, bookCopies_id integer not null, primary key (Reservation_id, bookCopies_id)) type=MyISAM;
create table USER (id integer not null auto_increment, email varchar(255) not null, login varchar(255) not null, name varchar(255) not null, phone_number varchar(255), surname varchar(255) not null, permission_id integer, primary key (id)) type=MyISAM;
create table USER_BORROW (User_id integer not null, borrows_id integer not null, primary key (User_id, borrows_id)) type=MyISAM;
create table USER_PENALTY (User_id integer not null, pentalties_id integer not null, primary key (User_id, pentalties_id)) type=MyISAM;
create table USER_RESERVATION (User_id integer not null, reservations_id integer not null, primary key (User_id, reservations_id)) type=MyISAM;
alter table BOOK add constraint UK_kkd7aa41jutasor701u64yvs8 unique (ISBN);
alter table BOOK_BOOK_COPY add constraint UK_4jquacwqg21y60g5g79b33uj9 unique (bookCopies_id);
alter table LANGUAGE_BOOK add constraint UK_7prrcqs4yydu44jqcgg9o86wb unique (books_id);
alter table PERMISSION_USER add constraint UK_bd23vse5j0wr4rg9dmrvxk6kq unique (users_id);
alter table PUBLISHER_BOOK add constraint UK_tmropp9l00ommd3hs9e3qk3xd unique (books_id);
alter table USER add constraint UK_oso07pudw19e66bs4yp8hwpux unique (email);
alter table USER add constraint UK_slockai06wyhy7i5c8vnd2o31 unique (login);
alter table USER_BORROW add constraint UK_jyj14utjyhuvqvbqxpeng34wt unique (borrows_id);
alter table USER_PENALTY add constraint UK_ag7acm4j2qsl0pn8j4id87r77 unique (pentalties_id);
alter table USER_RESERVATION add constraint UK_np2co3kslu8gcf6keqb0jtlh4 unique (reservations_id);
alter table AUTHOR_BOOK add constraint FK7vekgbhe0o6r0iaxku6rqtmie foreign key (books_id) references BOOK (id);
alter table AUTHOR_BOOK add constraint FK82yb03xr0gighwxf66390w1t2 foreign key (Author_id) references AUTHOR (id);
alter table BOOK add constraint FKctsex51u9k4o1k692uypo5t00 foreign key (language_id) references LANGUAGE (id);
alter table BOOK add constraint FKqvfng8guxc1p4jgft4c6sjrcd foreign key (publisher_id) references PUBLISHER (id);
alter table BOOK_AUTHOR add constraint FKjc7wg1x9yra815k3cgvqo8v64 foreign key (authors_id) references AUTHOR (id);
alter table BOOK_AUTHOR add constraint FKcpe3nnb7bay7fsg9uhphakt9s foreign key (Book_id) references BOOK (id);
alter table BOOK_BOOK_COPY add constraint FKorg1gomcecx1q78xkwbu5kc79 foreign key (bookCopies_id) references BOOK_COPY (id);
alter table BOOK_BOOK_COPY add constraint FK9jq1bxhgdrv407lhcs1hjytl0 foreign key (Book_id) references BOOK (id);
alter table BOOK_CATEGORY add constraint FKai7p5webscft71hw3copjod92 foreign key (categories_id) references CATEGORY (id);
alter table BOOK_CATEGORY add constraint FKj8rjeonbtbfsqvn9ew2huursj foreign key (Book_id) references BOOK (id);
alter table BOOK_COPY add constraint FKbahwm26a3cg9onugblc5aq3td foreign key (book_id) references BOOK (id);
alter table BOOK_COPY_BORROW add constraint FKg511yv16781e4d8r5krbdgy94 foreign key (borrows_id) references BORROW (id);
alter table BOOK_COPY_BORROW add constraint FK90o6g5wttou8k3jtw9ud30tg5 foreign key (BookCopy_id) references BOOK_COPY (id);
alter table BOOK_COPY_RESERVATION add constraint FK2pgxo6hvpb7tof572rmdhtryv foreign key (reservations_id) references RESERVATION (id);
alter table BOOK_COPY_RESERVATION add constraint FK3tvduqa0qpjk9dc7hnwaw7f95 foreign key (BookCopy_id) references BOOK_COPY (id);
alter table BORROW add constraint FKce9iriou0bnlby6330e9b05i6 foreign key (user_id) references USER (id);
alter table BORROW_BOOK_COPY add constraint FKqj0uacxa71rtnva8jo3cp0xol foreign key (bookCopies_id) references BOOK_COPY (id);
alter table BORROW_BOOK_COPY add constraint FKq2uv071mb9dypor7tp6ptay1a foreign key (Borrow_id) references BORROW (id);
alter table CATEGORY_BOOK add constraint FKg20fvru2uhyb9u8ubtdmnib29 foreign key (books_id) references BOOK (id);
alter table CATEGORY_BOOK add constraint FK4mas29dbqh20hj9rgrrx13013 foreign key (Category_id) references CATEGORY (id);
alter table LANGUAGE_BOOK add constraint FK9wkxyqt70q0pukvoa5c24ri29 foreign key (books_id) references BOOK (id);
alter table LANGUAGE_BOOK add constraint FKqft642svo0sti94uwlu5waqam foreign key (Language_id) references LANGUAGE (id);
alter table PENALTY add constraint FKm6ic8hkdurk2so2295is6vqxy foreign key (user_id) references USER (id);
alter table PERMISSION_USER add constraint FK8vn5mx7g6ol1hdwff69xyfvja foreign key (users_id) references USER (id);
alter table PERMISSION_USER add constraint FKmbvpou13d8y0j8qiv6p7vc3jk foreign key (Permission_id) references PERMISSION (id);
alter table PUBLISHER_BOOK add constraint FK806n7o30vj3ufdnloyxlkjoe4 foreign key (books_id) references BOOK (id);
alter table PUBLISHER_BOOK add constraint FK15kqxcu6f5bwp3idcg8jgxtlx foreign key (Publisher_id) references PUBLISHER (id);
alter table RESERVATION add constraint FKr2u2j7gugmek6gdo7e61mp6jr foreign key (user_id) references USER (id);
alter table RESERVATION_BOOK_COPY add constraint FKryg3x9u513huj6k35rlpk36t2 foreign key (bookCopies_id) references BOOK_COPY (id);
alter table RESERVATION_BOOK_COPY add constraint FKj0m5g695gl625cspf4ssqtjqc foreign key (Reservation_id) references RESERVATION (id);
alter table USER add constraint FK9wice7q5w80yx8dje6cagyyxy foreign key (permission_id) references PERMISSION (id);
alter table USER_BORROW add constraint FKpvdmboys8d467paj1sd1jcy74 foreign key (borrows_id) references BORROW (id);
alter table USER_BORROW add constraint FKlhguhf3hbl7nsngoh6xm3gh4i foreign key (User_id) references USER (id);
alter table USER_PENALTY add constraint FK81u3l9i52xqqv0891vfvmel6l foreign key (pentalties_id) references PENALTY (id);
alter table USER_PENALTY add constraint FKqhsiyis1y4uih88t7rahywdpt foreign key (User_id) references USER (id);
alter table USER_RESERVATION add constraint FKnp5rhwdh0bt4iyx3of4v9jbrv foreign key (reservations_id) references RESERVATION (id);
alter table USER_RESERVATION add constraint FK1tnvc1iymu3r1aj6mfvdo76vh foreign key (User_id) references USER (id);
drop table if exists AUTHOR;
drop table if exists AUTHOR_BOOK;
drop table if exists BOOK;
drop table if exists BOOK_AUTHOR;
drop table if exists BOOK_BOOK_COPY;
drop table if exists BOOK_CATEGORY;
drop table if exists BOOK_COPY;
drop table if exists BOOK_COPY_BORROW;
drop table if exists BOOK_COPY_RESERVATION;
drop table if exists BORROW;
drop table if exists BORROW_BOOK_COPY;
drop table if exists CATEGORY;
drop table if exists CATEGORY_BOOK;
drop table if exists LANGUAGE;
drop table if exists LANGUAGE_BOOK;
drop table if exists PENALTY;
drop table if exists PERMISSION;
drop table if exists PERMISSION_USER;
drop table if exists PUBLISHER;
drop table if exists PUBLISHER_BOOK;
drop table if exists RESERVATION;
drop table if exists RESERVATION_BOOK_COPY;
drop table if exists USER;
drop table if exists USER_BORROW;
drop table if exists USER_PENALTY;
drop table if exists USER_RESERVATION;
create table AUTHOR (id integer not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, primary key (id)) engine=MyISAM;
create table AUTHOR_BOOK (Author_id integer not null, books_id integer not null, primary key (Author_id, books_id)) engine=MyISAM;
create table BOOK (id integer not null, ISBN varchar(255), description varchar(255), edition integer not null, pages integer not null, publication_year smallint, title varchar(255) not null, language_id integer, publisher_id integer, primary key (id)) engine=MyISAM;
create table BOOK_AUTHOR (Book_id integer not null, authors_id integer not null, primary key (Book_id, authors_id)) engine=MyISAM;
create table BOOK_BOOK_COPY (Book_id integer not null, bookCopies_id integer not null, primary key (Book_id, bookCopies_id)) engine=MyISAM;
create table BOOK_CATEGORY (Book_id integer not null, categories_id integer not null, primary key (Book_id, categories_id)) engine=MyISAM;
create table BOOK_COPY (id integer not null auto_increment, status integer not null, book_id integer, primary key (id)) engine=MyISAM;
create table BOOK_COPY_BORROW (BookCopy_id integer not null, borrows_id integer not null, primary key (BookCopy_id, borrows_id)) engine=MyISAM;
create table BOOK_COPY_RESERVATION (BookCopy_id integer not null, reservations_id integer not null, primary key (BookCopy_id, reservations_id)) engine=MyISAM;
create table BORROW (id integer not null auto_increment, borrowed_on date not null, due_date date, returned date, user_id integer, primary key (id)) engine=MyISAM;
create table BORROW_BOOK_COPY (Borrow_id integer not null, bookCopies_id integer not null, primary key (Borrow_id, bookCopies_id)) engine=MyISAM;
create table CATEGORY (id integer not null auto_increment, name varchar(255) not null, primary key (id)) engine=MyISAM;
create table CATEGORY_BOOK (Category_id integer not null, books_id integer not null, primary key (Category_id, books_id)) engine=MyISAM;
create table LANGUAGE (id integer not null auto_increment, name varchar(255) not null, primary key (id)) engine=MyISAM;
create table LANGUAGE_BOOK (Language_id integer not null, books_id integer not null, primary key (Language_id, books_id)) engine=MyISAM;
create table PENALTY (id integer not null auto_increment, amount double precision not null, due_date date not null, interest double precision not null, user_id integer, primary key (id)) engine=MyISAM;
create table PERMISSION (id integer not null auto_increment, manage_all_users bit not null, manage_books bit not null, manage_members bit not null, primary key (id)) engine=MyISAM;
create table PERMISSION_USER (Permission_id integer not null, users_id integer not null, primary key (Permission_id, users_id)) engine=MyISAM;
create table PUBLISHER (id integer not null auto_increment, location varchar(255), name varchar(255) not null, primary key (id)) engine=MyISAM;
create table PUBLISHER_BOOK (Publisher_id integer not null, books_id integer not null, primary key (Publisher_id, books_id)) engine=MyISAM;
create table RESERVATION (id integer not null auto_increment, end_date date not null, start_date date not null, type varchar(255) not null, user_id integer, primary key (id)) engine=MyISAM;
create table RESERVATION_BOOK_COPY (Reservation_id integer not null, bookCopies_id integer not null, primary key (Reservation_id, bookCopies_id)) engine=MyISAM;
create table USER (id integer not null auto_increment, email varchar(255) not null, login varchar(255) not null, name varchar(255) not null, phone_number varchar(255), surname varchar(255) not null, permission_id integer, primary key (id)) engine=MyISAM;
create table USER_BORROW (User_id integer not null, borrows_id integer not null, primary key (User_id, borrows_id)) engine=MyISAM;
create table USER_PENALTY (User_id integer not null, pentalties_id integer not null, primary key (User_id, pentalties_id)) engine=MyISAM;
create table USER_RESERVATION (User_id integer not null, reservations_id integer not null, primary key (User_id, reservations_id)) engine=MyISAM;
alter table BOOK add constraint UK_kkd7aa41jutasor701u64yvs8 unique (ISBN);
alter table BOOK_BOOK_COPY add constraint UK_4jquacwqg21y60g5g79b33uj9 unique (bookCopies_id);
alter table LANGUAGE_BOOK add constraint UK_7prrcqs4yydu44jqcgg9o86wb unique (books_id);
alter table PERMISSION_USER add constraint UK_bd23vse5j0wr4rg9dmrvxk6kq unique (users_id);
alter table PUBLISHER_BOOK add constraint UK_tmropp9l00ommd3hs9e3qk3xd unique (books_id);
alter table USER add constraint UK_oso07pudw19e66bs4yp8hwpux unique (email);
alter table USER add constraint UK_slockai06wyhy7i5c8vnd2o31 unique (login);
alter table USER_BORROW add constraint UK_jyj14utjyhuvqvbqxpeng34wt unique (borrows_id);
alter table USER_PENALTY add constraint UK_ag7acm4j2qsl0pn8j4id87r77 unique (pentalties_id);
alter table USER_RESERVATION add constraint UK_np2co3kslu8gcf6keqb0jtlh4 unique (reservations_id);
alter table AUTHOR_BOOK add constraint FK7vekgbhe0o6r0iaxku6rqtmie foreign key (books_id) references BOOK (id);
alter table AUTHOR_BOOK add constraint FK82yb03xr0gighwxf66390w1t2 foreign key (Author_id) references AUTHOR (id);
alter table BOOK add constraint FKctsex51u9k4o1k692uypo5t00 foreign key (language_id) references LANGUAGE (id);
alter table BOOK add constraint FKqvfng8guxc1p4jgft4c6sjrcd foreign key (publisher_id) references PUBLISHER (id);
alter table BOOK_AUTHOR add constraint FKjc7wg1x9yra815k3cgvqo8v64 foreign key (authors_id) references AUTHOR (id);
alter table BOOK_AUTHOR add constraint FKcpe3nnb7bay7fsg9uhphakt9s foreign key (Book_id) references BOOK (id);
alter table BOOK_BOOK_COPY add constraint FKorg1gomcecx1q78xkwbu5kc79 foreign key (bookCopies_id) references BOOK_COPY (id);
alter table BOOK_BOOK_COPY add constraint FK9jq1bxhgdrv407lhcs1hjytl0 foreign key (Book_id) references BOOK (id);
alter table BOOK_CATEGORY add constraint FKai7p5webscft71hw3copjod92 foreign key (categories_id) references CATEGORY (id);
alter table BOOK_CATEGORY add constraint FKj8rjeonbtbfsqvn9ew2huursj foreign key (Book_id) references BOOK (id);
alter table BOOK_COPY add constraint FKbahwm26a3cg9onugblc5aq3td foreign key (book_id) references BOOK (id);
alter table BOOK_COPY_BORROW add constraint FKg511yv16781e4d8r5krbdgy94 foreign key (borrows_id) references BORROW (id);
alter table BOOK_COPY_BORROW add constraint FK90o6g5wttou8k3jtw9ud30tg5 foreign key (BookCopy_id) references BOOK_COPY (id);
alter table BOOK_COPY_RESERVATION add constraint FK2pgxo6hvpb7tof572rmdhtryv foreign key (reservations_id) references RESERVATION (id);
alter table BOOK_COPY_RESERVATION add constraint FK3tvduqa0qpjk9dc7hnwaw7f95 foreign key (BookCopy_id) references BOOK_COPY (id);
alter table BORROW add constraint FKce9iriou0bnlby6330e9b05i6 foreign key (user_id) references USER (id);
alter table BORROW_BOOK_COPY add constraint FKqj0uacxa71rtnva8jo3cp0xol foreign key (bookCopies_id) references BOOK_COPY (id);
alter table BORROW_BOOK_COPY add constraint FKq2uv071mb9dypor7tp6ptay1a foreign key (Borrow_id) references BORROW (id);
alter table CATEGORY_BOOK add constraint FKg20fvru2uhyb9u8ubtdmnib29 foreign key (books_id) references BOOK (id);
alter table CATEGORY_BOOK add constraint FK4mas29dbqh20hj9rgrrx13013 foreign key (Category_id) references CATEGORY (id);
alter table LANGUAGE_BOOK add constraint FK9wkxyqt70q0pukvoa5c24ri29 foreign key (books_id) references BOOK (id);
alter table LANGUAGE_BOOK add constraint FKqft642svo0sti94uwlu5waqam foreign key (Language_id) references LANGUAGE (id);
alter table PENALTY add constraint FKm6ic8hkdurk2so2295is6vqxy foreign key (user_id) references USER (id);
alter table PERMISSION_USER add constraint FK8vn5mx7g6ol1hdwff69xyfvja foreign key (users_id) references USER (id);
alter table PERMISSION_USER add constraint FKmbvpou13d8y0j8qiv6p7vc3jk foreign key (Permission_id) references PERMISSION (id);
alter table PUBLISHER_BOOK add constraint FK806n7o30vj3ufdnloyxlkjoe4 foreign key (books_id) references BOOK (id);
alter table PUBLISHER_BOOK add constraint FK15kqxcu6f5bwp3idcg8jgxtlx foreign key (Publisher_id) references PUBLISHER (id);
alter table RESERVATION add constraint FKr2u2j7gugmek6gdo7e61mp6jr foreign key (user_id) references USER (id);
alter table RESERVATION_BOOK_COPY add constraint FKryg3x9u513huj6k35rlpk36t2 foreign key (bookCopies_id) references BOOK_COPY (id);
alter table RESERVATION_BOOK_COPY add constraint FKj0m5g695gl625cspf4ssqtjqc foreign key (Reservation_id) references RESERVATION (id);
alter table USER add constraint FK9wice7q5w80yx8dje6cagyyxy foreign key (permission_id) references PERMISSION (id);
alter table USER_BORROW add constraint FKpvdmboys8d467paj1sd1jcy74 foreign key (borrows_id) references BORROW (id);
alter table USER_BORROW add constraint FKlhguhf3hbl7nsngoh6xm3gh4i foreign key (User_id) references USER (id);
alter table USER_PENALTY add constraint FK81u3l9i52xqqv0891vfvmel6l foreign key (pentalties_id) references PENALTY (id);
alter table USER_PENALTY add constraint FKqhsiyis1y4uih88t7rahywdpt foreign key (User_id) references USER (id);
alter table USER_RESERVATION add constraint FKnp5rhwdh0bt4iyx3of4v9jbrv foreign key (reservations_id) references RESERVATION (id);
alter table USER_RESERVATION add constraint FK1tnvc1iymu3r1aj6mfvdo76vh foreign key (User_id) references USER (id);
drop table if exists AUTHOR;
drop table if exists AUTHOR_BOOK;
drop table if exists BOOK;
drop table if exists BOOK_AUTHOR;
drop table if exists BOOK_BOOK_COPY;
drop table if exists BOOK_CATEGORY;
drop table if exists BOOK_COPY;
drop table if exists BOOK_COPY_BORROW;
drop table if exists BOOK_COPY_RESERVATION;
drop table if exists BORROW;
drop table if exists BORROW_BOOK_COPY;
drop table if exists CATEGORY;
drop table if exists CATEGORY_BOOK;
drop table if exists LANGUAGE;
drop table if exists LANGUAGE_BOOK;
drop table if exists PENALTY;
drop table if exists PERMISSION;
drop table if exists PERMISSION_USER;
drop table if exists PUBLISHER;
drop table if exists PUBLISHER_BOOK;
drop table if exists RESERVATION;
drop table if exists RESERVATION_BOOK_COPY;
drop table if exists USER;
drop table if exists USER_BORROW;
drop table if exists USER_PENALTY;
drop table if exists USER_RESERVATION;
create table AUTHOR (id integer not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, primary key (id)) engine=MyISAM;
create table AUTHOR_BOOK (Author_id integer not null, books_id integer not null, primary key (Author_id, books_id)) engine=MyISAM;
create table BOOK (id integer not null, ISBN varchar(255), description varchar(255), edition integer not null, pages integer not null, publication_year smallint, title varchar(255) not null, language_id integer, publisher_id integer, primary key (id)) engine=MyISAM;
create table BOOK_AUTHOR (Book_id integer not null, authors_id integer not null, primary key (Book_id, authors_id)) engine=MyISAM;
create table BOOK_BOOK_COPY (Book_id integer not null, bookCopies_id integer not null, primary key (Book_id, bookCopies_id)) engine=MyISAM;
create table BOOK_CATEGORY (Book_id integer not null, categories_id integer not null, primary key (Book_id, categories_id)) engine=MyISAM;
create table BOOK_COPY (id integer not null auto_increment, status integer not null, book_id integer, primary key (id)) engine=MyISAM;
create table BOOK_COPY_BORROW (BookCopy_id integer not null, borrows_id integer not null, primary key (BookCopy_id, borrows_id)) engine=MyISAM;
create table BOOK_COPY_RESERVATION (BookCopy_id integer not null, reservations_id integer not null, primary key (BookCopy_id, reservations_id)) engine=MyISAM;
create table BORROW (id integer not null auto_increment, borrowed_on date not null, due_date date, returned date, user_id integer, primary key (id)) engine=MyISAM;
create table BORROW_BOOK_COPY (Borrow_id integer not null, bookCopies_id integer not null, primary key (Borrow_id, bookCopies_id)) engine=MyISAM;
create table CATEGORY (id integer not null auto_increment, name varchar(255) not null, primary key (id)) engine=MyISAM;
create table CATEGORY_BOOK (Category_id integer not null, books_id integer not null, primary key (Category_id, books_id)) engine=MyISAM;
create table LANGUAGE (id integer not null auto_increment, name varchar(255) not null, primary key (id)) engine=MyISAM;
create table LANGUAGE_BOOK (Language_id integer not null, books_id integer not null, primary key (Language_id, books_id)) engine=MyISAM;
create table PENALTY (id integer not null auto_increment, amount double precision not null, due_date date not null, interest double precision not null, user_id integer, primary key (id)) engine=MyISAM;
create table PERMISSION (id integer not null auto_increment, manage_all_users bit not null, manage_books bit not null, manage_members bit not null, primary key (id)) engine=MyISAM;
create table PERMISSION_USER (Permission_id integer not null, users_id integer not null, primary key (Permission_id, users_id)) engine=MyISAM;
create table PUBLISHER (id integer not null auto_increment, location varchar(255), name varchar(255) not null, primary key (id)) engine=MyISAM;
create table PUBLISHER_BOOK (Publisher_id integer not null, books_id integer not null, primary key (Publisher_id, books_id)) engine=MyISAM;
create table RESERVATION (id integer not null auto_increment, end_date date not null, start_date date not null, type varchar(255) not null, user_id integer, primary key (id)) engine=MyISAM;
create table RESERVATION_BOOK_COPY (Reservation_id integer not null, bookCopies_id integer not null, primary key (Reservation_id, bookCopies_id)) engine=MyISAM;
create table USER (id integer not null auto_increment, email varchar(255) not null, login varchar(255) not null, name varchar(255) not null, phone_number varchar(255), surname varchar(255) not null, permission_id integer, primary key (id)) engine=MyISAM;
create table USER_BORROW (User_id integer not null, borrows_id integer not null, primary key (User_id, borrows_id)) engine=MyISAM;
create table USER_PENALTY (User_id integer not null, pentalties_id integer not null, primary key (User_id, pentalties_id)) engine=MyISAM;
create table USER_RESERVATION (User_id integer not null, reservations_id integer not null, primary key (User_id, reservations_id)) engine=MyISAM;
alter table BOOK add constraint UK_kkd7aa41jutasor701u64yvs8 unique (ISBN);
alter table BOOK_BOOK_COPY add constraint UK_4jquacwqg21y60g5g79b33uj9 unique (bookCopies_id);
alter table LANGUAGE_BOOK add constraint UK_7prrcqs4yydu44jqcgg9o86wb unique (books_id);
alter table PERMISSION_USER add constraint UK_bd23vse5j0wr4rg9dmrvxk6kq unique (users_id);
alter table PUBLISHER_BOOK add constraint UK_tmropp9l00ommd3hs9e3qk3xd unique (books_id);
alter table USER add constraint UK_oso07pudw19e66bs4yp8hwpux unique (email);
alter table USER add constraint UK_slockai06wyhy7i5c8vnd2o31 unique (login);
alter table USER_BORROW add constraint UK_jyj14utjyhuvqvbqxpeng34wt unique (borrows_id);
alter table USER_PENALTY add constraint UK_ag7acm4j2qsl0pn8j4id87r77 unique (pentalties_id);
alter table USER_RESERVATION add constraint UK_np2co3kslu8gcf6keqb0jtlh4 unique (reservations_id);
alter table AUTHOR_BOOK add constraint FK7vekgbhe0o6r0iaxku6rqtmie foreign key (books_id) references BOOK (id);
alter table AUTHOR_BOOK add constraint FK82yb03xr0gighwxf66390w1t2 foreign key (Author_id) references AUTHOR (id);
alter table BOOK add constraint FKctsex51u9k4o1k692uypo5t00 foreign key (language_id) references LANGUAGE (id);
alter table BOOK add constraint FKqvfng8guxc1p4jgft4c6sjrcd foreign key (publisher_id) references PUBLISHER (id);
alter table BOOK_AUTHOR add constraint FKjc7wg1x9yra815k3cgvqo8v64 foreign key (authors_id) references AUTHOR (id);
alter table BOOK_AUTHOR add constraint FKcpe3nnb7bay7fsg9uhphakt9s foreign key (Book_id) references BOOK (id);
alter table BOOK_BOOK_COPY add constraint FKorg1gomcecx1q78xkwbu5kc79 foreign key (bookCopies_id) references BOOK_COPY (id);
alter table BOOK_BOOK_COPY add constraint FK9jq1bxhgdrv407lhcs1hjytl0 foreign key (Book_id) references BOOK (id);
alter table BOOK_CATEGORY add constraint FKai7p5webscft71hw3copjod92 foreign key (categories_id) references CATEGORY (id);
alter table BOOK_CATEGORY add constraint FKj8rjeonbtbfsqvn9ew2huursj foreign key (Book_id) references BOOK (id);
alter table BOOK_COPY add constraint FKbahwm26a3cg9onugblc5aq3td foreign key (book_id) references BOOK (id);
alter table BOOK_COPY_BORROW add constraint FKg511yv16781e4d8r5krbdgy94 foreign key (borrows_id) references BORROW (id);
alter table BOOK_COPY_BORROW add constraint FK90o6g5wttou8k3jtw9ud30tg5 foreign key (BookCopy_id) references BOOK_COPY (id);
alter table BOOK_COPY_RESERVATION add constraint FK2pgxo6hvpb7tof572rmdhtryv foreign key (reservations_id) references RESERVATION (id);
alter table BOOK_COPY_RESERVATION add constraint FK3tvduqa0qpjk9dc7hnwaw7f95 foreign key (BookCopy_id) references BOOK_COPY (id);
alter table BORROW add constraint FKce9iriou0bnlby6330e9b05i6 foreign key (user_id) references USER (id);
alter table BORROW_BOOK_COPY add constraint FKqj0uacxa71rtnva8jo3cp0xol foreign key (bookCopies_id) references BOOK_COPY (id);
alter table BORROW_BOOK_COPY add constraint FKq2uv071mb9dypor7tp6ptay1a foreign key (Borrow_id) references BORROW (id);
alter table CATEGORY_BOOK add constraint FKg20fvru2uhyb9u8ubtdmnib29 foreign key (books_id) references BOOK (id);
alter table CATEGORY_BOOK add constraint FK4mas29dbqh20hj9rgrrx13013 foreign key (Category_id) references CATEGORY (id);
alter table LANGUAGE_BOOK add constraint FK9wkxyqt70q0pukvoa5c24ri29 foreign key (books_id) references BOOK (id);
alter table LANGUAGE_BOOK add constraint FKqft642svo0sti94uwlu5waqam foreign key (Language_id) references LANGUAGE (id);
alter table PENALTY add constraint FKm6ic8hkdurk2so2295is6vqxy foreign key (user_id) references USER (id);
alter table PERMISSION_USER add constraint FK8vn5mx7g6ol1hdwff69xyfvja foreign key (users_id) references USER (id);
alter table PERMISSION_USER add constraint FKmbvpou13d8y0j8qiv6p7vc3jk foreign key (Permission_id) references PERMISSION (id);
alter table PUBLISHER_BOOK add constraint FK806n7o30vj3ufdnloyxlkjoe4 foreign key (books_id) references BOOK (id);
alter table PUBLISHER_BOOK add constraint FK15kqxcu6f5bwp3idcg8jgxtlx foreign key (Publisher_id) references PUBLISHER (id);
alter table RESERVATION add constraint FKr2u2j7gugmek6gdo7e61mp6jr foreign key (user_id) references USER (id);
alter table RESERVATION_BOOK_COPY add constraint FKryg3x9u513huj6k35rlpk36t2 foreign key (bookCopies_id) references BOOK_COPY (id);
alter table RESERVATION_BOOK_COPY add constraint FKj0m5g695gl625cspf4ssqtjqc foreign key (Reservation_id) references RESERVATION (id);
alter table USER add constraint FK9wice7q5w80yx8dje6cagyyxy foreign key (permission_id) references PERMISSION (id);
alter table USER_BORROW add constraint FKpvdmboys8d467paj1sd1jcy74 foreign key (borrows_id) references BORROW (id);
alter table USER_BORROW add constraint FKlhguhf3hbl7nsngoh6xm3gh4i foreign key (User_id) references USER (id);
alter table USER_PENALTY add constraint FK81u3l9i52xqqv0891vfvmel6l foreign key (pentalties_id) references PENALTY (id);
alter table USER_PENALTY add constraint FKqhsiyis1y4uih88t7rahywdpt foreign key (User_id) references USER (id);
alter table USER_RESERVATION add constraint FKnp5rhwdh0bt4iyx3of4v9jbrv foreign key (reservations_id) references RESERVATION (id);
alter table USER_RESERVATION add constraint FK1tnvc1iymu3r1aj6mfvdo76vh foreign key (User_id) references USER (id);
drop table if exists AUTHOR;
drop table if exists AUTHOR_BOOK;
drop table if exists BOOK;
drop table if exists BOOK_AUTHOR;
drop table if exists BOOK_BOOK_COPY;
drop table if exists BOOK_CATEGORY;
drop table if exists BOOK_COPY;
drop table if exists BOOK_COPY_BORROW;
drop table if exists BOOK_COPY_RESERVATION;
drop table if exists BORROW;
drop table if exists BORROW_BOOK_COPY;
drop table if exists CATEGORY;
drop table if exists CATEGORY_BOOK;
drop table if exists LANGUAGE;
drop table if exists LANGUAGE_BOOK;
drop table if exists PENALTY;
drop table if exists PERMISSION;
drop table if exists PERMISSION_USER;
drop table if exists PUBLISHER;
drop table if exists PUBLISHER_BOOK;
drop table if exists RESERVATION;
drop table if exists RESERVATION_BOOK_COPY;
drop table if exists USER;
drop table if exists USER_BORROW;
drop table if exists USER_PENALTY;
drop table if exists USER_RESERVATION;
create table AUTHOR (id integer not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, primary key (id)) engine=MyISAM;
create table AUTHOR_BOOK (Author_id integer not null, books_id integer not null, primary key (Author_id, books_id)) engine=MyISAM;
create table BOOK (id integer not null, ISBN varchar(255), description varchar(255), edition integer not null, pages integer not null, publication_year smallint, title varchar(255) not null, language_id integer, publisher_id integer, primary key (id)) engine=MyISAM;
create table BOOK_AUTHOR (Book_id integer not null, authors_id integer not null, primary key (Book_id, authors_id)) engine=MyISAM;
create table BOOK_BOOK_COPY (Book_id integer not null, bookCopies_id integer not null, primary key (Book_id, bookCopies_id)) engine=MyISAM;
create table BOOK_CATEGORY (Book_id integer not null, categories_id integer not null, primary key (Book_id, categories_id)) engine=MyISAM;
create table BOOK_COPY (id integer not null auto_increment, status integer not null, book_id integer, primary key (id)) engine=MyISAM;
create table BOOK_COPY_BORROW (BookCopy_id integer not null, borrows_id integer not null, primary key (BookCopy_id, borrows_id)) engine=MyISAM;
create table BOOK_COPY_RESERVATION (BookCopy_id integer not null, reservations_id integer not null, primary key (BookCopy_id, reservations_id)) engine=MyISAM;
create table BORROW (id integer not null auto_increment, borrowed_on date not null, due_date date, returned date, user_id integer, primary key (id)) engine=MyISAM;
create table BORROW_BOOK_COPY (Borrow_id integer not null, bookCopies_id integer not null, primary key (Borrow_id, bookCopies_id)) engine=MyISAM;
create table CATEGORY (id integer not null auto_increment, name varchar(255) not null, primary key (id)) engine=MyISAM;
create table CATEGORY_BOOK (Category_id integer not null, books_id integer not null, primary key (Category_id, books_id)) engine=MyISAM;
create table LANGUAGE (id integer not null auto_increment, name varchar(255) not null, primary key (id)) engine=MyISAM;
create table LANGUAGE_BOOK (Language_id integer not null, books_id integer not null, primary key (Language_id, books_id)) engine=MyISAM;
create table PENALTY (id integer not null auto_increment, amount double precision not null, due_date date not null, interest double precision not null, user_id integer, primary key (id)) engine=MyISAM;
create table PERMISSION (id integer not null auto_increment, manage_all_users bit not null, manage_books bit not null, manage_members bit not null, primary key (id)) engine=MyISAM;
create table PERMISSION_USER (Permission_id integer not null, users_id integer not null, primary key (Permission_id, users_id)) engine=MyISAM;
create table PUBLISHER (id integer not null auto_increment, location varchar(255), name varchar(255) not null, primary key (id)) engine=MyISAM;
create table PUBLISHER_BOOK (Publisher_id integer not null, books_id integer not null, primary key (Publisher_id, books_id)) engine=MyISAM;
create table RESERVATION (id integer not null auto_increment, end_date date not null, start_date date not null, type varchar(255) not null, user_id integer, primary key (id)) engine=MyISAM;
create table RESERVATION_BOOK_COPY (Reservation_id integer not null, bookCopies_id integer not null, primary key (Reservation_id, bookCopies_id)) engine=MyISAM;
create table USER (id integer not null auto_increment, email varchar(255) not null, login varchar(255) not null, name varchar(255) not null, password varchar(255) not null, phone_number varchar(255), surname varchar(255) not null, permission_id integer, primary key (id)) engine=MyISAM;
create table USER_BORROW (User_id integer not null, borrows_id integer not null, primary key (User_id, borrows_id)) engine=MyISAM;
create table USER_PENALTY (User_id integer not null, pentalties_id integer not null, primary key (User_id, pentalties_id)) engine=MyISAM;
create table USER_RESERVATION (User_id integer not null, reservations_id integer not null, primary key (User_id, reservations_id)) engine=MyISAM;
alter table BOOK add constraint UK_kkd7aa41jutasor701u64yvs8 unique (ISBN);
alter table BOOK_BOOK_COPY add constraint UK_4jquacwqg21y60g5g79b33uj9 unique (bookCopies_id);
alter table LANGUAGE_BOOK add constraint UK_7prrcqs4yydu44jqcgg9o86wb unique (books_id);
alter table PERMISSION_USER add constraint UK_bd23vse5j0wr4rg9dmrvxk6kq unique (users_id);
alter table PUBLISHER_BOOK add constraint UK_tmropp9l00ommd3hs9e3qk3xd unique (books_id);
alter table USER add constraint UK_oso07pudw19e66bs4yp8hwpux unique (email);
alter table USER add constraint UK_slockai06wyhy7i5c8vnd2o31 unique (login);
alter table USER_BORROW add constraint UK_jyj14utjyhuvqvbqxpeng34wt unique (borrows_id);
alter table USER_PENALTY add constraint UK_ag7acm4j2qsl0pn8j4id87r77 unique (pentalties_id);
alter table USER_RESERVATION add constraint UK_np2co3kslu8gcf6keqb0jtlh4 unique (reservations_id);
alter table AUTHOR_BOOK add constraint FK7vekgbhe0o6r0iaxku6rqtmie foreign key (books_id) references BOOK (id);
alter table AUTHOR_BOOK add constraint FK82yb03xr0gighwxf66390w1t2 foreign key (Author_id) references AUTHOR (id);
alter table BOOK add constraint FKctsex51u9k4o1k692uypo5t00 foreign key (language_id) references LANGUAGE (id);
alter table BOOK add constraint FKqvfng8guxc1p4jgft4c6sjrcd foreign key (publisher_id) references PUBLISHER (id);
alter table BOOK_AUTHOR add constraint FKjc7wg1x9yra815k3cgvqo8v64 foreign key (authors_id) references AUTHOR (id);
alter table BOOK_AUTHOR add constraint FKcpe3nnb7bay7fsg9uhphakt9s foreign key (Book_id) references BOOK (id);
alter table BOOK_BOOK_COPY add constraint FKorg1gomcecx1q78xkwbu5kc79 foreign key (bookCopies_id) references BOOK_COPY (id);
alter table BOOK_BOOK_COPY add constraint FK9jq1bxhgdrv407lhcs1hjytl0 foreign key (Book_id) references BOOK (id);
alter table BOOK_CATEGORY add constraint FKai7p5webscft71hw3copjod92 foreign key (categories_id) references CATEGORY (id);
alter table BOOK_CATEGORY add constraint FKj8rjeonbtbfsqvn9ew2huursj foreign key (Book_id) references BOOK (id);
alter table BOOK_COPY add constraint FKbahwm26a3cg9onugblc5aq3td foreign key (book_id) references BOOK (id);
alter table BOOK_COPY_BORROW add constraint FKg511yv16781e4d8r5krbdgy94 foreign key (borrows_id) references BORROW (id);
alter table BOOK_COPY_BORROW add constraint FK90o6g5wttou8k3jtw9ud30tg5 foreign key (BookCopy_id) references BOOK_COPY (id);
alter table BOOK_COPY_RESERVATION add constraint FK2pgxo6hvpb7tof572rmdhtryv foreign key (reservations_id) references RESERVATION (id);
alter table BOOK_COPY_RESERVATION add constraint FK3tvduqa0qpjk9dc7hnwaw7f95 foreign key (BookCopy_id) references BOOK_COPY (id);
alter table BORROW add constraint FKce9iriou0bnlby6330e9b05i6 foreign key (user_id) references USER (id);
alter table BORROW_BOOK_COPY add constraint FKqj0uacxa71rtnva8jo3cp0xol foreign key (bookCopies_id) references BOOK_COPY (id);
alter table BORROW_BOOK_COPY add constraint FKq2uv071mb9dypor7tp6ptay1a foreign key (Borrow_id) references BORROW (id);
alter table CATEGORY_BOOK add constraint FKg20fvru2uhyb9u8ubtdmnib29 foreign key (books_id) references BOOK (id);
alter table CATEGORY_BOOK add constraint FK4mas29dbqh20hj9rgrrx13013 foreign key (Category_id) references CATEGORY (id);
alter table LANGUAGE_BOOK add constraint FK9wkxyqt70q0pukvoa5c24ri29 foreign key (books_id) references BOOK (id);
alter table LANGUAGE_BOOK add constraint FKqft642svo0sti94uwlu5waqam foreign key (Language_id) references LANGUAGE (id);
alter table PENALTY add constraint FKm6ic8hkdurk2so2295is6vqxy foreign key (user_id) references USER (id);
alter table PERMISSION_USER add constraint FK8vn5mx7g6ol1hdwff69xyfvja foreign key (users_id) references USER (id);
alter table PERMISSION_USER add constraint FKmbvpou13d8y0j8qiv6p7vc3jk foreign key (Permission_id) references PERMISSION (id);
alter table PUBLISHER_BOOK add constraint FK806n7o30vj3ufdnloyxlkjoe4 foreign key (books_id) references BOOK (id);
alter table PUBLISHER_BOOK add constraint FK15kqxcu6f5bwp3idcg8jgxtlx foreign key (Publisher_id) references PUBLISHER (id);
alter table RESERVATION add constraint FKr2u2j7gugmek6gdo7e61mp6jr foreign key (user_id) references USER (id);
alter table RESERVATION_BOOK_COPY add constraint FKryg3x9u513huj6k35rlpk36t2 foreign key (bookCopies_id) references BOOK_COPY (id);
alter table RESERVATION_BOOK_COPY add constraint FKj0m5g695gl625cspf4ssqtjqc foreign key (Reservation_id) references RESERVATION (id);
alter table USER add constraint FK9wice7q5w80yx8dje6cagyyxy foreign key (permission_id) references PERMISSION (id);
alter table USER_BORROW add constraint FKpvdmboys8d467paj1sd1jcy74 foreign key (borrows_id) references BORROW (id);
alter table USER_BORROW add constraint FKlhguhf3hbl7nsngoh6xm3gh4i foreign key (User_id) references USER (id);
alter table USER_PENALTY add constraint FK81u3l9i52xqqv0891vfvmel6l foreign key (pentalties_id) references PENALTY (id);
alter table USER_PENALTY add constraint FKqhsiyis1y4uih88t7rahywdpt foreign key (User_id) references USER (id);
alter table USER_RESERVATION add constraint FKnp5rhwdh0bt4iyx3of4v9jbrv foreign key (reservations_id) references RESERVATION (id);
alter table USER_RESERVATION add constraint FK1tnvc1iymu3r1aj6mfvdo76vh foreign key (User_id) references USER (id);
drop table if exists AUTHOR;
drop table if exists AUTHOR_BOOK;
drop table if exists BOOK;
drop table if exists BOOK_AUTHOR;
drop table if exists BOOK_BOOK_COPY;
drop table if exists BOOK_CATEGORY;
drop table if exists BOOK_COPY;
drop table if exists BOOK_COPY_BORROW;
drop table if exists BOOK_COPY_RESERVATION;
drop table if exists BORROW;
drop table if exists BORROW_BOOK_COPY;
drop table if exists CATEGORY;
drop table if exists CATEGORY_BOOK;
drop table if exists LANGUAGE;
drop table if exists LANGUAGE_BOOK;
drop table if exists PENALTY;
drop table if exists PERMISSION;
drop table if exists PERMISSION_USER;
drop table if exists PUBLISHER;
drop table if exists PUBLISHER_BOOK;
drop table if exists RESERVATION;
drop table if exists RESERVATION_BOOK_COPY;
drop table if exists USER;
drop table if exists USER_BORROW;
drop table if exists USER_PENALTY;
drop table if exists USER_RESERVATION;
create table AUTHOR (id integer not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, primary key (id)) engine=MyISAM;
create table AUTHOR_BOOK (Author_id integer not null, books_id integer not null, primary key (Author_id, books_id)) engine=MyISAM;
create table BOOK (id integer not null, ISBN varchar(255), description varchar(255), edition integer not null, pages integer not null, publication_year smallint, title varchar(255) not null, language_id integer, publisher_id integer, primary key (id)) engine=MyISAM;
create table BOOK_AUTHOR (Book_id integer not null, authors_id integer not null, primary key (Book_id, authors_id)) engine=MyISAM;
create table BOOK_BOOK_COPY (Book_id integer not null, bookCopies_id integer not null, primary key (Book_id, bookCopies_id)) engine=MyISAM;
create table BOOK_CATEGORY (Book_id integer not null, categories_id integer not null, primary key (Book_id, categories_id)) engine=MyISAM;
create table BOOK_COPY (id integer not null auto_increment, status integer not null, book_id integer, primary key (id)) engine=MyISAM;
create table BOOK_COPY_BORROW (BookCopy_id integer not null, borrows_id integer not null, primary key (BookCopy_id, borrows_id)) engine=MyISAM;
create table BOOK_COPY_RESERVATION (BookCopy_id integer not null, reservations_id integer not null, primary key (BookCopy_id, reservations_id)) engine=MyISAM;
create table BORROW (id integer not null auto_increment, borrowed_on date not null, due_date date, returned date, user_id integer, primary key (id)) engine=MyISAM;
create table BORROW_BOOK_COPY (Borrow_id integer not null, bookCopies_id integer not null, primary key (Borrow_id, bookCopies_id)) engine=MyISAM;
create table CATEGORY (id integer not null auto_increment, name varchar(255) not null, primary key (id)) engine=MyISAM;
create table CATEGORY_BOOK (Category_id integer not null, books_id integer not null, primary key (Category_id, books_id)) engine=MyISAM;
create table LANGUAGE (id integer not null auto_increment, name varchar(255) not null, primary key (id)) engine=MyISAM;
create table LANGUAGE_BOOK (Language_id integer not null, books_id integer not null, primary key (Language_id, books_id)) engine=MyISAM;
create table PENALTY (id integer not null auto_increment, amount double precision not null, due_date date not null, interest double precision not null, user_id integer, primary key (id)) engine=MyISAM;
create table PERMISSION (id integer not null auto_increment, manage_all_users bit not null, manage_books bit not null, manage_members bit not null, primary key (id)) engine=MyISAM;
create table PERMISSION_USER (Permission_id integer not null, users_id integer not null, primary key (Permission_id, users_id)) engine=MyISAM;
create table PUBLISHER (id integer not null auto_increment, location varchar(255), name varchar(255) not null, primary key (id)) engine=MyISAM;
create table PUBLISHER_BOOK (Publisher_id integer not null, books_id integer not null, primary key (Publisher_id, books_id)) engine=MyISAM;
create table RESERVATION (id integer not null auto_increment, end_date date not null, start_date date not null, type varchar(255) not null, user_id integer, primary key (id)) engine=MyISAM;
create table RESERVATION_BOOK_COPY (Reservation_id integer not null, bookCopies_id integer not null, primary key (Reservation_id, bookCopies_id)) engine=MyISAM;
create table USER (id integer not null auto_increment, email varchar(255) not null, login varchar(255) not null, name varchar(255) not null, password varchar(255) not null, phone_number varchar(255), surname varchar(255) not null, permission_id integer, primary key (id)) engine=MyISAM;
create table USER_BORROW (User_id integer not null, borrows_id integer not null, primary key (User_id, borrows_id)) engine=MyISAM;
create table USER_PENALTY (User_id integer not null, pentalties_id integer not null, primary key (User_id, pentalties_id)) engine=MyISAM;
create table USER_RESERVATION (User_id integer not null, reservations_id integer not null, primary key (User_id, reservations_id)) engine=MyISAM;
alter table BOOK add constraint UK_kkd7aa41jutasor701u64yvs8 unique (ISBN);
alter table BOOK_BOOK_COPY add constraint UK_4jquacwqg21y60g5g79b33uj9 unique (bookCopies_id);
alter table LANGUAGE_BOOK add constraint UK_7prrcqs4yydu44jqcgg9o86wb unique (books_id);
alter table PERMISSION_USER add constraint UK_bd23vse5j0wr4rg9dmrvxk6kq unique (users_id);
alter table PUBLISHER_BOOK add constraint UK_tmropp9l00ommd3hs9e3qk3xd unique (books_id);
alter table USER add constraint UK_oso07pudw19e66bs4yp8hwpux unique (email);
alter table USER add constraint UK_slockai06wyhy7i5c8vnd2o31 unique (login);
alter table USER_BORROW add constraint UK_jyj14utjyhuvqvbqxpeng34wt unique (borrows_id);
alter table USER_PENALTY add constraint UK_ag7acm4j2qsl0pn8j4id87r77 unique (pentalties_id);
alter table USER_RESERVATION add constraint UK_np2co3kslu8gcf6keqb0jtlh4 unique (reservations_id);
alter table AUTHOR_BOOK add constraint FK7vekgbhe0o6r0iaxku6rqtmie foreign key (books_id) references BOOK (id);
alter table AUTHOR_BOOK add constraint FK82yb03xr0gighwxf66390w1t2 foreign key (Author_id) references AUTHOR (id);
alter table BOOK add constraint FKctsex51u9k4o1k692uypo5t00 foreign key (language_id) references LANGUAGE (id);
alter table BOOK add constraint FKqvfng8guxc1p4jgft4c6sjrcd foreign key (publisher_id) references PUBLISHER (id);
alter table BOOK_AUTHOR add constraint FKjc7wg1x9yra815k3cgvqo8v64 foreign key (authors_id) references AUTHOR (id);
alter table BOOK_AUTHOR add constraint FKcpe3nnb7bay7fsg9uhphakt9s foreign key (Book_id) references BOOK (id);
alter table BOOK_BOOK_COPY add constraint FKorg1gomcecx1q78xkwbu5kc79 foreign key (bookCopies_id) references BOOK_COPY (id);
alter table BOOK_BOOK_COPY add constraint FK9jq1bxhgdrv407lhcs1hjytl0 foreign key (Book_id) references BOOK (id);
alter table BOOK_CATEGORY add constraint FKai7p5webscft71hw3copjod92 foreign key (categories_id) references CATEGORY (id);
alter table BOOK_CATEGORY add constraint FKj8rjeonbtbfsqvn9ew2huursj foreign key (Book_id) references BOOK (id);
alter table BOOK_COPY add constraint FKbahwm26a3cg9onugblc5aq3td foreign key (book_id) references BOOK (id);
alter table BOOK_COPY_BORROW add constraint FKg511yv16781e4d8r5krbdgy94 foreign key (borrows_id) references BORROW (id);
alter table BOOK_COPY_BORROW add constraint FK90o6g5wttou8k3jtw9ud30tg5 foreign key (BookCopy_id) references BOOK_COPY (id);
alter table BOOK_COPY_RESERVATION add constraint FK2pgxo6hvpb7tof572rmdhtryv foreign key (reservations_id) references RESERVATION (id);
alter table BOOK_COPY_RESERVATION add constraint FK3tvduqa0qpjk9dc7hnwaw7f95 foreign key (BookCopy_id) references BOOK_COPY (id);
alter table BORROW add constraint FKce9iriou0bnlby6330e9b05i6 foreign key (user_id) references USER (id);
alter table BORROW_BOOK_COPY add constraint FKqj0uacxa71rtnva8jo3cp0xol foreign key (bookCopies_id) references BOOK_COPY (id);
alter table BORROW_BOOK_COPY add constraint FKq2uv071mb9dypor7tp6ptay1a foreign key (Borrow_id) references BORROW (id);
alter table CATEGORY_BOOK add constraint FKg20fvru2uhyb9u8ubtdmnib29 foreign key (books_id) references BOOK (id);
alter table CATEGORY_BOOK add constraint FK4mas29dbqh20hj9rgrrx13013 foreign key (Category_id) references CATEGORY (id);
alter table LANGUAGE_BOOK add constraint FK9wkxyqt70q0pukvoa5c24ri29 foreign key (books_id) references BOOK (id);
alter table LANGUAGE_BOOK add constraint FKqft642svo0sti94uwlu5waqam foreign key (Language_id) references LANGUAGE (id);
alter table PENALTY add constraint FKm6ic8hkdurk2so2295is6vqxy foreign key (user_id) references USER (id);
alter table PERMISSION_USER add constraint FK8vn5mx7g6ol1hdwff69xyfvja foreign key (users_id) references USER (id);
alter table PERMISSION_USER add constraint FKmbvpou13d8y0j8qiv6p7vc3jk foreign key (Permission_id) references PERMISSION (id);
alter table PUBLISHER_BOOK add constraint FK806n7o30vj3ufdnloyxlkjoe4 foreign key (books_id) references BOOK (id);
alter table PUBLISHER_BOOK add constraint FK15kqxcu6f5bwp3idcg8jgxtlx foreign key (Publisher_id) references PUBLISHER (id);
alter table RESERVATION add constraint FKr2u2j7gugmek6gdo7e61mp6jr foreign key (user_id) references USER (id);
alter table RESERVATION_BOOK_COPY add constraint FKryg3x9u513huj6k35rlpk36t2 foreign key (bookCopies_id) references BOOK_COPY (id);
alter table RESERVATION_BOOK_COPY add constraint FKj0m5g695gl625cspf4ssqtjqc foreign key (Reservation_id) references RESERVATION (id);
alter table USER add constraint FK9wice7q5w80yx8dje6cagyyxy foreign key (permission_id) references PERMISSION (id);
alter table USER_BORROW add constraint FKpvdmboys8d467paj1sd1jcy74 foreign key (borrows_id) references BORROW (id);
alter table USER_BORROW add constraint FKlhguhf3hbl7nsngoh6xm3gh4i foreign key (User_id) references USER (id);
alter table USER_PENALTY add constraint FK81u3l9i52xqqv0891vfvmel6l foreign key (pentalties_id) references PENALTY (id);
alter table USER_PENALTY add constraint FKqhsiyis1y4uih88t7rahywdpt foreign key (User_id) references USER (id);
alter table USER_RESERVATION add constraint FKnp5rhwdh0bt4iyx3of4v9jbrv foreign key (reservations_id) references RESERVATION (id);
alter table USER_RESERVATION add constraint FK1tnvc1iymu3r1aj6mfvdo76vh foreign key (User_id) references USER (id);
